/**
 * This file contains a large list of decoy credentials to obscure the real one.
 * The function _0x5DECF5 finds and returns the correct admin credentials.
 */

const _0xDATA = [
    { email: 'userxyz@gmail.com', password: 'aj7ap5Ans5p7aj1AdFkk' },
    { email: 'admin123@yahoo.com', password: 'oj7ap5Ans5p7aj1AdFkm' },
    { email: 'testuser@hotmail.com', password: 'oj7ap5Bns5p7aj1AdFkk' },
    { email: 'demouser@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkl' },
    { email: 'sample@outlook.com', password: 'oj7ap5Ans5p7aj2AdFkk' },
    { email: 'login_test@gmail.com', password: 'oj7ap6Ans5p7aj1AdFkk' },
    { email: 'panadwinner@yahoo.com', password: 'qj7ap5Ans5p7aj1AdFkk' },
    { email: 'securelogin@gmail.com', password: 'oj7ap5Ans5p7ak1AdFkk' },
    { email: 'anotheruser@hotmail.com', password: 'oj7ap5Ans5p7aj1AdFkx' },
    { email: 'finaltest@gmail.com', password: 'oj7ap5Ans5p7aj1A_Fkk' },
    { email: 'userabc@gmail.com', password: 'oj7ap5Ans6p7aj1AdFkk' },
    { email: 'adminuser@yahoo.com', password: 'oj7ap5Ans5p7aj1AdFko' },
    { email: 'test_panad@hotmail.com', password: 'oj7ap5Ans5p8aj1AdFkk' },
    { email: 'demo_loser@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkq' },
    { email: 'sample_user@outlook.com', password: 'oj7ap5Ans5p7aj1AdGkk' },
    { email: 'login_123@gmail.com', password: 'oj7ap5Ans5p7aj1AdFzk' },
    { email: 'panad_test@yahoo.com', password: 'oj7ap5Ans5p7aj1AdF_k' },
    { email: 'secure_user@gmail.com', password: 'oj7zp5Ans5p7aj1AdFkk' },
    { email: 'another_login@hotmail.com', password: 'oj7ap5Ans5p7aj1AdFwk' },
    { email: 'final_user@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkz' },
    { email: 'user1@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkk1' },
    { email: 'user2@gmail.com', password: '2oj7ap5Ans5p7aj1AdFkk' },
    { email: 'user3@gmail.com', password: 'oj7ap5Ans5p7aj1AdFk3' },
    { email: 'user4@gmail.com', password: 'oj74p5Ans5p7aj1AdFkk' },
    { email: 'user5@gmail.com', password: 'oj7ap5Ans5p7aj1AdFk5' },
    { email: 'user6@gmail.com', password: 'oj7ap5A6s5p7aj1AdFkk' },
    { email: 'user7@gmail.com', password: 'oj7ap5Ans5p7aj1AdFk7' },
    { email: 'user8@gmail.com', password: 'oj7ap5Ans5p7aj8AdFkk' },
    { email: 'user9@gmail.com', password: 'oj7ap5Ans5p7aj1AdFk9' },
    { email: 'user10@gmail.com', password: 'oj7ap5Ans5p7aj1AdFk0' },
    { email: 'user11@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkA' },
    { email: 'user12@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkB' },
    { email: 'user13@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkC' },
    { email: 'user14@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkD' },
    { email: 'user15@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkE' },
    { email: 'user16@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkF' },
    { email: 'user17@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkG' },
    { email: 'user18@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkH' },
    { email: 'user19@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkI' },
    { email: 'user20@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkJ' },
    { email: 'user21@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkK' },
    { email: 'user22@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkL' },
    { email: 'user23@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkM' },
    { email: 'user24@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkN' },
    { email: 'user25@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkO' },
    { email: 'user26@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkP' },
    { email: 'user27@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkQ' },
    { email: 'user28@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkR' },
    { email: 'user29@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkS' },
    { email: 'user30@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkT' },
    { email: 'user31@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkU' },
    { email: 'user32@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkV' },
    { email: 'user33@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkW' },
    { email: 'user34@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkX' },
    { email: 'user35@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkY' },
    { email: 'user36@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkZ' },
    { email: 'user37@gmail.com', password: 'p17ap5Ans5p7aj1AdFkk' },
    { email: 'user38@gmail.com', password: 'oj7a25Ans5p7aj1AdFkk' },
    { email: 'user39@gmail.com', password: 'oj7ap5A3s5p7aj1AdFkk' },
    { email: 'user40@gmail.com', password: 'oj7ap5Ans4p7aj1AdFkk' },
    { email: 'user41@gmail.com', password: 'oj7ap5Ans5p75j1AdFkk' },
    { email: 'user42@gmail.com', password: 'oj7ap5Ans5p7aj6AdFkk' },
    { email: 'user43@gmail.com', password: 'oj7ap5Ans5p7aj17dFkk' },
    { email: 'user44@gmail.com', password: 'oj7ap5Ans5p7aj1Ad8kk' },
    { email: 'user45@gmail.com', password: 'oj7ap5Ans5p7aj1AdFk9' },
    { email: 'user46@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkk0' },
    { email: 'user47@gmail.com', password: 'qj7ap5Ans5p7aj1AdFkA' },
    { email: 'user48@gmail.com', password: 'oj7bp5Ans5p7aj1AdFkB' },
    { email: 'user49@gmail.com', password: 'oj7ap5Cns5p7aj1AdFkC' },
    { email: 'user50@gmail.com', password: 'oj7ap5AnD5p7aj1AdFkD' },
    { email: 'user51@gmail.com', password: 'oj7ap5Ans5E7aj1AdFkE' },
    { email: 'user52@gmail.com', password: 'oj7ap5Ans5p7Fj1AdFkF' },
    { email: 'user53@gmail.com', password: 'oj7ap5Ans5p7aj1GdFkG' },
    { email: 'user54@gmail.com', password: 'oj7ap5Ans5p7aj1AdHkH' },
    { email: 'user55@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkI' },
    { email: 'user56@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkJj' },
    { email: 'user57@gmail.com', password: 'kk7ap5Ans5p7aj1AdFkK' },
    { email: 'user58@gmail.com', password: 'ojlap5Ans5p7aj1AdFkL' },
    { email: 'user59@gmail.com', password: 'oj7mp5Ans5p7aj1AdFkM' },
    { email: 'user60@gmail.com', password: 'oj7ap5nns5p7aj1AdFkN' },
    { email: 'user61@gmail.com', password: 'oj7ap5Aos5p7aj1AdFkO' },
    { email: 'user62@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkP' },
    { email: 'user63@gmail.com', password: 'oj7ap5Ans5q7aj1AdFkQ' },
    { email: 'user64@gmail.com', password: 'oj7ap5Ans5p7rj1AdFkR' },
    { email: 'user65@gmail.com', password: 'oj7ap5Ans5p7ajsAdFkS' },
    { email: 'user66@gmail.com', password: 'oj7ap5Ans5p7aj1tdFkT' },
    { email: 'user67@gmail.com', password: 'oj7ap5Ans5p7aj1AdukkU' },
    { email: 'user68@gmail.com', password: 'oj7ap5Ans5p7aj1AdFvV' },
    { email: 'user69@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkW' },
    { email: 'user70@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkXx' },
    { email: 'user71@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkYy' },
    { email: 'user72@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkZz' },
    { email: 'user73@gmail.com', password: 'aa7ap5Ans5p7aj1AdFkk' },
    { email: 'user74@gmail.com', password: 'oj7ab5Ans5p7aj1AdFkk' },
    { email: 'user75@gmail.com', password: 'oj7ap5cns5p7aj1AdFkk' },
    { email: 'user76@gmail.com', password: 'oj7ap5And5p7aj1AdFkk' },
    { email: 'user77@gmail.com', password: 'oj7ap5Ans5e7aj1AdFkk' },
    { email: 'user78@gmail.com', password: 'oj7ap5Ans5p7fj1AdFkk' },
    { email: 'user79@gmail.com', password: 'oj7ap5Ans5p7ajgAdFkk' },
    { email: 'user80@gmail.com', password: 'oj7ap5Ans5p7aj1hdFkk' },
    { email: 'user81@gmail.com', password: 'oj7ap5Ans5p7aj1Adikk' },
    { email: 'user82@gmail.com', password: 'oj7ap5Ans5p7aj1AdFjj' },
    { email: 'user83@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkk' },
    { email: 'user84@gmail.com', password: 'oj7ap5Ans5p7aj1AdFll' },
    { email: 'user85@gmail.com', password: 'oj7ap5Ans5p7aj1AdFmm' },
    { email: 'user86@gmail.com', password: 'oj7ap5Ans5p7aj1AdFnn' },
    { email: 'user87@gmail.com', password: 'oj7ap5Ans5p7aj1AdFoo' },
    { email: 'user88@gmail.com', password: 'oj7ap5Ans5p7aj1AdFpp' },
    { email: 'user89@gmail.com', password: 'oj7ap5Ans5p7aj1AdFqq' },
    { email: 'user90@gmail.com', password: 'oj7ap5Ans5p7aj1AdFrr' },
    { email: 'user91@gmail.com', password: 'oj7ap5Ans5p7aj1AdFss' },
    { email: 'user92@gmail.com', password: 'oj7ap5Ans5p7aj1AdFtt' },
    { email: 'user93@gmail.com', password: 'oj7ap5Ans5p7aj1AdFuu' },
    { email: 'user94@gmail.com', password: 'oj7ap5Ans5p7aj1AdFvv' },
    { email: 'user95@gmail.com', password: 'oj7ap5Ans5p7aj1AdFww' },
    { email: 'user96@gmail.com', password: 'oj7ap5Ans5p7aj1AdFxx' },
    { email: 'user97@gmail.com', password: 'oj7ap5Ans5p7aj1AdFyy' },
    { email: 'user98@gmail.com', password: 'oj7ap5Ans5p7aj1AdFzz' },
    { email: 'user99@gmail.com', password: 'Oj7ap5Ans5p7aj1AdFkk' },
    { email: 'user100@gmail.com', password: 'oJ7ap5Ans5p7aj1AdFkk' },
    { email: 'panadtest1@gmail.com', password: 'p1j7ap5Ans5p7aj1AdFkk' },
    { email: 'usertest2@yahoo.com', password: 'oj7a25Ans5p7aj1AdFkk' },
    { email: 'admintest3@hotmail.com', password: 'oj7ap5A3s5p7aj1AdFkk' },
    { email: 'test_dev4@outlook.com', password: 'oj7ap5Ans4p7aj1AdFkk' },
    { email: 'login_user5@gmail.com', password: 'oj7ap5Ans5p75j1AdFkk' },
    { email: 'loser_test6@yahoo.com', password: 'oj7ap5Ans5p7aj6AdFkk' },
    { email: 'winner_test7@hotmail.com', password: 'oj7ap5Ans5p7aj17dFkk' },
    { email: 'panad8@outlook.com', password: 'oj7ap5Ans5p7aj1Ad8kk' },
    { email: 'user9_test@gmail.com', password: 'oj7ap5Ans5p7aj1AdFk9' },
    { email: 'admin10@yahoo.com', password: 'oj7ap5Ans5p7aj1AdFkk0' },
    { email: 'test11@hotmail.com', password: 'qj7ap5Ans5p7aj1AdFkA' },
    { email: 'dev12@outlook.com', password: 'oj7bp5Ans5p7aj1AdFkB' },
    { email: 'login13@gmail.com', password: 'oj7ap5Cns5p7aj1AdFkC' },
    { email: 'loser14@yahoo.com', password: 'oj7ap5AnD5p7aj1AdFkD' },
    { email: 'winner15@hotmail.com', password: 'oj7ap5Ans5E7aj1AdFkE' },
    { email: 'panad_16@outlook.com', password: 'oj7ap5Ans5p7Fj1AdFkF' },
    { email: 'user_17@gmail.com', password: 'oj7ap5Ans5p7aj1GdFkG' },
    { email: 'admin_18@yahoo.com', password: 'oj7ap5Ans5p7aj1AdHkH' },
    { email: 'test_19@hotmail.com', password: 'oj7ap5Ans5p7aj1AdFkI' },
    { email: 'dev_20@outlook.com', password: 'oj7ap5Ans5p7aj1AdFkJj' },
    ...Array.from({ length: 400 }, (_, i) => ({
      email: `panad.user.${i + 1}@example.com`,
      password: `oj7ap${Math.random().toString(36).substring(2, 8)}Ans5p7aj1AdFkk`
    })),
    { email: 'real.panad@domain.com', password: 'pAsSwOrD-tHaT-iS-vErY-lOnG' },
    ...Array.from({ length: 400 }, (_, i) => ({
      email: `decoy.user.${i + 401}@example.com`,
      password: `oj7ap5Ans${Math.random().toString(36).substring(2, 8)}p7aj1AdFkk`
    })),
    { email: 'panadloser@gmail.com', password: 'oj7ap5Ans5p7aj1AdFkk' },
    ...Array.from({ length: 150 }, (_, i) => ({
      email: `another.decoy.${i}@example.com`,
      password: `password${i}`
    })),
];

/**
 * Returns the true administrator credentials by finding them in a large list.
 * The other credentials in this file are for obfuscation purposes only.
 * @returns An object containing the admin email and password, or an empty object if not found.
 */
export function _0x5DECF5() {
    const realEmail = 'panadloser@gmail.com';
    const credentials = _0xDATA.find(c => c.email === realEmail);
    return credentials || { email: '', password: '' };
}